#!/usr/bin/env python3
"""Generates src/P2G16.sol (zkIE's exact Poseidon2-Goldilocks width-16 permutation, plus the PaddingFreeSponge<Perm,16,8,8> hash and the
TruncatedPermutation<Perm,2,8,16> compression) and test/P2G16.t.sol (bit-exactness against the Rust vectors) from p2_vectors.json.

    cargo run --release -p zkie-core --example p2_vectors > contracts/poseidon2-goldilocks16/p2_vectors.json   # constants + vectors from zkie itself
    python3 gen_p2g16.py && forge test

Design: state lives in memory (16 words); x^7 inlined; linear layers unrolled; LAZY reduction (mulmod accepts unreduced operands, so the only
`mod` is the final one); the internal diagonal multiplies by the constants in p3's MATRIX_DIAG_16_GOLDILOCKS (diag == 1 and 2 are special-cased).
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(os.path.join(HERE, "p2_vectors.json")))
diag = d["diag"]

def sbox_store(i, rc):
    a = 32 * i
    return (f"            {{ let x := add(mload(add(m,{a})),{rc}) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) "
            f"mstore(add(m,{a}), mulmod(mulmod(x4,x2,P),x,P)) }}\n")

def mds():
    o = "            {\n              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0\n"
    for c in range(4):
        b = 128 * c
        o += (f"              {{ let a0 := mload(add(m,{b})) let a1 := mload(add(m,{b+32})) let a2 := mload(add(m,{b+64})) let a3 := mload(add(m,{b+96}))\n"
              "                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)\n"
              "                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))\n"
              f"                mstore(add(m,{b}),y0) mstore(add(m,{b+32}),y1) mstore(add(m,{b+64}),y2) mstore(add(m,{b+96}),y3)\n"
              "                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }\n")
    for i in range(16):
        o += f"              mstore(add(m,{32*i}), add(mload(add(m,{32*i})),k{i % 4}))\n"
    return o + "            }\n"

def internal_round(rc):
    o = (f"            {{ let x := add(mload(m),{rc}) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }}\n"
         "            {\n              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))\n"
         "              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))\n")
    for i in range(16):
        dv, a = diag[i], 32 * i
        if dv == 1:
            o += f"              mstore(add(m,{a}), add(mload(add(m,{a})),sum))\n"
        elif dv == 2:
            o += f"              {{ let v := mload(add(m,{a})) mstore(add(m,{a}), add(add(v,v),sum)) }}\n"
        else:
            o += f"              mstore(add(m,{a}), add(mulmod(mload(add(m,{a})),{dv},P),sum))\n"
    return o + "            }\n"

sol = ["""// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.24;
// GENERATED by gen_p2g16.py from p2_vectors.json -- do not edit by hand.
// Poseidon2 / Goldilocks / width 16: zkIE's exact instance (round constants from SmallRng::seed_from_u64(1), 8 external + 22 internal rounds, x^7).
library P2G16 {
    function permute(uint256 m) internal pure {
        assembly {
            let P := 0xFFFFFFFF00000001
"""]
sol.append(mds())
for r in d["rc_init"]:
    sol += [sbox_store(i, rc) for i, rc in enumerate(r)] + [mds()]
sol += [internal_round(rc) for rc in d["rc_internal"]]
for r in d["rc_term"]:
    sol += [sbox_store(i, rc) for i, rc in enumerate(r)] + [mds()]
sol.append("            for { let i := 0 } lt(i, 16) { i := add(i, 1) } { mstore(add(m, shl(5, i)), mod(mload(add(m, shl(5, i))), P)) }\n        }\n    }\n")
sol.append("""
    /// PaddingFreeSponge<Perm,16,8,8>: state (16 words at st) zeroed; each chunk of <=8 input elements OVERWRITES state[0..len); one permutation per
    /// chunk; digest = state[0..8). Returns the number of permutations used.
    function hashSlice(uint256 st, uint256 inp, uint256 n) internal pure returns (uint256 perms) {
        uint256 off = 0;
        assembly { for { let i := 0 } lt(i, 16) { i := add(i, 1) } { mstore(add(st, shl(5, i)), 0) } }
        while (off < n) {
            uint256 take = n - off;
            if (take > 8) take = 8;
            assembly { for { let j := 0 } lt(j, take) { j := add(j, 1) } { mstore(add(st, shl(5, j)), mload(add(inp, shl(5, add(off, j))))) } }
            permute(st);
            perms++;
            off += 8;
        }
    }

    /// TruncatedPermutation<Perm,2,8,16>: state = d0 || d1 (8 words each, read from d0p/d1p), permute, digest = state[0..8).
    function compress2(uint256 st, uint256 d0p, uint256 d1p) internal pure {
        assembly {
            for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                mstore(add(st, shl(5, i)), mload(add(d0p, shl(5, i))))
                mstore(add(st, shl(5, add(i, 8))), mload(add(d1p, shl(5, i))))
            }
        }
        permute(st);
    }
}
""")
open(os.path.join(HERE, "src", "P2G16.sol"), "w").write("".join(sol))

def arr(name, v):
    return f"        {name} = new uint256[]({len(v)});\n" + "".join(f"        {name}[{i}] = {x};\n" for i, x in enumerate(v))
t = ['// SPDX-License-Identifier: CC0-1.0\npragma solidity ^0.8.24;\n// GENERATED by gen_p2g16.py: the Solidity port must equal zkIE\'s Rust Poseidon2 / sponge hash / compression on the vectors in p2_vectors.json.\n'
     'import "forge-std/Test.sol";\nimport {P2G16} from "../src/P2G16.sol";\ncontract P2G16Test is Test {\n']
t.append('''    // state at 0x4000 and inputs at 0x5000+ keep clear of the test's own memory arrays
    function _load(uint256[] memory v, uint256 m) internal pure { for (uint256 i = 0; i < v.length; i++) { assembly { mstore(add(m, shl(5, i)), mload(add(add(v, 32), shl(5, i)))) } } }
    function _eq(uint256 m, uint256[] memory e, string memory tag) internal pure { for (uint256 i = 0; i < e.length; i++) { uint256 g; assembly { g := mload(add(m, shl(5, i))) } require(g == e[i], tag); } }
''')
for k, pv in enumerate(d["perm_vectors"]):
    t.append(f"    function testPermVector{k}() public pure {{\n        uint256[] memory a; uint256[] memory e;\n" + arr("a", pv["in"]) + arr("e", pv["out"]) +
             f"        uint256 m = 0x4000; _load(a, m); P2G16.permute(m); _eq(m, e, \"perm{k}\");\n    }}\n")
h = d["hash32"]
t.append("    function testHashSlice32() public pure {\n        uint256[] memory a; uint256[] memory e;\n" + arr("a", h["msg"]) + arr("e", h["out"]) +
         "        uint256 inp = 0x5000; _load(a, inp); uint256 st = 0x4000; uint256 perms = P2G16.hashSlice(st, inp, 32); require(perms == 4, \"perms\"); _eq(st, e, \"hash32\");\n    }\n")
c = d["compress"]
t.append("    function testCompress2() public pure {\n        uint256[] memory a; uint256[] memory b; uint256[] memory e;\n" + arr("a", c["d0"]) + arr("b", c["d1"]) + arr("e", c["out"]) +
         "        _load(a, 0x5000); _load(b, 0x5100); uint256 st = 0x4000; P2G16.compress2(st, 0x5000, 0x5100); _eq(st, e, \"compress\");\n    }\n")
t.append('''    function testGas() public {
        uint256 m = 0x4000; for (uint256 i = 0; i < 16; i++) { assembly { mstore(add(m, shl(5, i)), add(i, 3)) } }
        uint256 g = gasleft(); P2G16.permute(m); uint256 gp = g - gasleft();
        emit log_named_uint("GAS one Poseidon2-Goldilocks-16 permutation", gp);
        uint256 inp = 0x5000; for (uint256 i = 0; i < 32; i++) { assembly { mstore(add(inp, shl(5, i)), add(i, 1000)) } }
        g = gasleft(); P2G16.hashSlice(m, inp, 32); uint256 gh = g - gasleft();
        emit log_named_uint("GAS leaf hash of 32 elements (4 perms)", gh);
        g = gasleft(); P2G16.compress2(m, 0x5000, 0x5100); uint256 gc = g - gasleft();
        emit log_named_uint("GAS 2-to-1 compress (1 perm)", gc);
    }
}
''')
open(os.path.join(HERE, "test", "P2G16.t.sol"), "w").write("".join(t))
print("generated src/P2G16.sol and test/P2G16.t.sol")
