[package]
name = "zkie-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v0.4.0", features = ["circuit-params"] }
libc = "0.2"
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
thiserror = "1"
zkie-compiler = { path = "../zkie-compiler" }
zkie-core = { path = "../zkie-core" }
zkie-types = { path = "../zkie-types" }

[dev-dependencies]
blake3 = "1"
serde_json = "1"
