// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.24;
// GENERATED by gen_p2g16.py from p2_vectors.json -- do not edit by hand.
// Poseidon2 / Goldilocks / width 16: zkIE's exact instance (round constants from SmallRng::seed_from_u64(1), 8 external + 22 internal rounds, x^7).
library P2G16 {
    function permute(uint256 m) internal pure {
        assembly {
            let P := 0xFFFFFFFF00000001
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(add(m,0)),14971601782005023387) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),13781649495232077965) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),1847458086238483744) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),13765271635752736470) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),3406718355780431780) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),10892412867582108485) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),18204613561675945223) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),9655336933892813345) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),1781989159761824720) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),2477283028068920342) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),16978024111547606601) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),6336475467619303347) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),1336129645694042326) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),7278725533440954441) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),1650926874576718010) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),2884092293074692283) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(add(m,0)),10277292511068429730) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),8723528388573605619) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),17670016435951889822) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),11847526622624223050) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),4869519043768407819) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),14645621260580619786) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),2927941368235978475) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),7627105703721172900) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),4384663367605854827) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),11119034730948704880) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),3397900810577180010) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),18115970067406137490) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),11274606161466886392) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),13467911786374401590) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),10949103424463861935) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),11981483663808188895) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(add(m,0)),9358210361682609782) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),11442939244776437245) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),17602980262171424054) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),5959474180322755185) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),1996769245947054333) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),13544632058761996522) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),16649296193330087156) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),12760326241867116135) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),8675954731918215884) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),9203961167189488855) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),7142459279718377197) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),14896067320733876238) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),10513651835548663426) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),10980731235462242881) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),11545633344504843399) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),3681332405582117356) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(add(m,0)),1551717361741363511) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),1089825986224478220) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),13743543109493793873) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),10495706909903888189) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),5741824577281331454) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),2863871085027299347) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),8020316667640232903) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),9030324100812113514) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),4060453892939860073) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),4812952906290940755) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),7288938975096551135) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),1523413163938920386) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),3218723287451184873) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),8519291637136269967) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),15569404087299740275) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),6675309140374977304) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(m),4392373542327609504) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),8344969226188502370) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),9770557976685836172) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),17709893575142651223) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),17006648832550909060) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),2793767156639733416) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),3203092373748215709) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),16527458165576072202) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),9313026833118211659) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),18130815229803419832) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),5591875450551198428) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),5356442613253376964) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),14258758100088769485) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),6957056376317387463) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),11534989657919123786) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),3303577726227566018) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),11638538016851270185) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),482942180874268528) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),11581761061203396628) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),10415959143182103107) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),896292667846012975) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(m),986351733063280855) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(m, mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let sum := add(add(add(mload(m),mload(add(m,32))),add(mload(add(m,64)),mload(add(m,96)))),add(add(mload(add(m,128)),mload(add(m,160))),add(mload(add(m,192)),mload(add(m,224)))))
              sum := add(sum,add(add(add(mload(add(m,256)),mload(add(m,288))),add(mload(add(m,320)),mload(add(m,352)))),add(add(mload(add(m,384)),mload(add(m,416))),add(mload(add(m,448)),mload(add(m,480))))))
              mstore(add(m,0), add(mulmod(mload(add(m,0)),18446744069414584319,P),sum))
              mstore(add(m,32), add(mload(add(m,32)),sum))
              { let v := mload(add(m,64)) mstore(add(m,64), add(add(v,v),sum)) }
              mstore(add(m,96), add(mulmod(mload(add(m,96)),9223372034707292161,P),sum))
              mstore(add(m,128), add(mulmod(mload(add(m,128)),3,P),sum))
              mstore(add(m,160), add(mulmod(mload(add(m,160)),4,P),sum))
              mstore(add(m,192), add(mulmod(mload(add(m,192)),9223372034707292160,P),sum))
              mstore(add(m,224), add(mulmod(mload(add(m,224)),18446744069414584318,P),sum))
              mstore(add(m,256), add(mulmod(mload(add(m,256)),18446744069414584317,P),sum))
              mstore(add(m,288), add(mulmod(mload(add(m,288)),16140901060737761281,P),sum))
              mstore(add(m,320), add(mulmod(mload(add(m,320)),17293822565076172801,P),sum))
              mstore(add(m,352), add(mulmod(mload(add(m,352)),17870283317245378561,P),sum))
              mstore(add(m,384), add(mulmod(mload(add(m,384)),2305843008676823040,P),sum))
              mstore(add(m,416), add(mulmod(mload(add(m,416)),1152921504338411520,P),sum))
              mstore(add(m,448), add(mulmod(mload(add(m,448)),576460752169205760,P),sum))
              mstore(add(m,480), add(mulmod(mload(add(m,480)),18446744065119617026,P),sum))
            }
            { let x := add(mload(add(m,0)),13277019641707655070) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),16054962663855284350) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),16118477356065450490) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),12450144969344350533) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),3016971212554844115) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),10106950261373826276) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),4179636441425175325) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),7701408363278597845) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),14132919861472972135) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),4690934053664561485) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),6507992417881854455) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),10539423570466705693) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),3871134291889952231) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),2114177653741543929) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),17952667377880274780) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),2532941421210460225) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(add(m,0)),5590743015620664857) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),10647004009443905139) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),2130185805889187749) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),4519654305690755293) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),16491131029958018403) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),9934593392938298225) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),10687777565311169786) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),4818658302970458788) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),7592769082020283814) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),3490444722094131318) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),17011666529252910057) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),6550753962735948862) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),10586833208941192493) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),11176138021902761615) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),15105089592917451306) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),15421734318183186012) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(add(m,0)),5749635752403345000) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),4090615369751998369) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),16703745955471597755) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),1409755919872153883) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),9032299486790008961) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),14478229173361157616) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),7732777553312921958) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),13485783050051125300) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),6570804143645159706) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),16959442802773171189) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),5952666585052063944) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),6269872033900258072) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),746891881542659304) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),9468919674514586239) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),6864277846436576001) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),8961602886297693672) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            { let x := add(mload(add(m,0)),8838261370623181961) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,0), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,32)),5934988284481276974) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,32), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,64)),7831665578625736880) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,64), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,96)),15596874342601540480) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,96), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,128)),17556590255179281850) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,128), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,160)),3547542339717257703) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,160), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,192)),13225335229113436365) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,192), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,224)),11584950822049631825) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,224), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,256)),8859162147496220813) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,256), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,288)),4999916698893990530) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,288), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,320)),13174580208074147882) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,320), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,352)),10727057610277631597) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,352), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,384)),5647878954534158281) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,384), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,416)),17295642051858334462) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,416), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,448)),17716604360544609748) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,448), mulmod(mulmod(x4,x2,P),x,P)) }
            { let x := add(mload(add(m,480)),4661544233612770916) let x2 := mulmod(x,x,P) let x4 := mulmod(x2,x2,P) mstore(add(m,480), mulmod(mulmod(x4,x2,P),x,P)) }
            {
              let k0 := 0 let k1 := 0 let k2 := 0 let k3 := 0
              { let a0 := mload(add(m,0)) let a1 := mload(add(m,32)) let a2 := mload(add(m,64)) let a3 := mload(add(m,96))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,0),y0) mstore(add(m,32),y1) mstore(add(m,64),y2) mstore(add(m,96),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,128)) let a1 := mload(add(m,160)) let a2 := mload(add(m,192)) let a3 := mload(add(m,224))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,128),y0) mstore(add(m,160),y1) mstore(add(m,192),y2) mstore(add(m,224),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,256)) let a1 := mload(add(m,288)) let a2 := mload(add(m,320)) let a3 := mload(add(m,352))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,256),y0) mstore(add(m,288),y1) mstore(add(m,320),y2) mstore(add(m,352),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              { let a0 := mload(add(m,384)) let a1 := mload(add(m,416)) let a2 := mload(add(m,448)) let a3 := mload(add(m,480))
                let t01 := add(a0,a1) let t23 := add(a2,a3) let t0123 := add(t01,t23) let t01123 := add(t0123,a1) let t01233 := add(t0123,a3)
                let y0 := add(t01123,t01) let y1 := add(t01123,add(a2,a2)) let y2 := add(t01233,t23) let y3 := add(t01233,add(a0,a0))
                mstore(add(m,384),y0) mstore(add(m,416),y1) mstore(add(m,448),y2) mstore(add(m,480),y3)
                k0 := add(k0,y0) k1 := add(k1,y1) k2 := add(k2,y2) k3 := add(k3,y3) }
              mstore(add(m,0), add(mload(add(m,0)),k0))
              mstore(add(m,32), add(mload(add(m,32)),k1))
              mstore(add(m,64), add(mload(add(m,64)),k2))
              mstore(add(m,96), add(mload(add(m,96)),k3))
              mstore(add(m,128), add(mload(add(m,128)),k0))
              mstore(add(m,160), add(mload(add(m,160)),k1))
              mstore(add(m,192), add(mload(add(m,192)),k2))
              mstore(add(m,224), add(mload(add(m,224)),k3))
              mstore(add(m,256), add(mload(add(m,256)),k0))
              mstore(add(m,288), add(mload(add(m,288)),k1))
              mstore(add(m,320), add(mload(add(m,320)),k2))
              mstore(add(m,352), add(mload(add(m,352)),k3))
              mstore(add(m,384), add(mload(add(m,384)),k0))
              mstore(add(m,416), add(mload(add(m,416)),k1))
              mstore(add(m,448), add(mload(add(m,448)),k2))
              mstore(add(m,480), add(mload(add(m,480)),k3))
            }
            for { let i := 0 } lt(i, 16) { i := add(i, 1) } { mstore(add(m, shl(5, i)), mod(mload(add(m, shl(5, i))), P)) }
        }
    }

    /// PaddingFreeSponge<Perm,16,8,8>: state (16 words at st) zeroed; each chunk of <=8 input elements OVERWRITES state[0..len); one permutation per
    /// chunk; digest = state[0..8). Returns the number of permutations used.
    function hashSlice(uint256 st, uint256 inp, uint256 n) internal pure returns (uint256 perms) {
        uint256 off = 0;
        assembly { for { let i := 0 } lt(i, 16) { i := add(i, 1) } { mstore(add(st, shl(5, i)), 0) } }
        while (off < n) {
            uint256 take = n - off;
            if (take > 8) take = 8;
            assembly { for { let j := 0 } lt(j, take) { j := add(j, 1) } { mstore(add(st, shl(5, j)), mload(add(inp, shl(5, add(off, j))))) } }
            permute(st);
            perms++;
            off += 8;
        }
    }

    /// TruncatedPermutation<Perm,2,8,16>: state = d0 || d1 (8 words each, read from d0p/d1p), permute, digest = state[0..8).
    function compress2(uint256 st, uint256 d0p, uint256 d1p) internal pure {
        assembly {
            for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                mstore(add(st, shl(5, i)), mload(add(d0p, shl(5, i))))
                mstore(add(st, shl(5, add(i, 8))), mload(add(d1p, shl(5, i))))
            }
        }
        permute(st);
    }
}
