// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.24;
// GENERATED by gen_p2g16.py: the Solidity port must equal zkIE's Rust Poseidon2 / sponge hash / compression on the vectors in p2_vectors.json.
import "forge-std/Test.sol";
import {P2G16} from "../src/P2G16.sol";
contract P2G16Test is Test {
    // state at 0x4000 and inputs at 0x5000+ keep clear of the test's own memory arrays
    function _load(uint256[] memory v, uint256 m) internal pure { for (uint256 i = 0; i < v.length; i++) { assembly { mstore(add(m, shl(5, i)), mload(add(add(v, 32), shl(5, i)))) } } }
    function _eq(uint256 m, uint256[] memory e, string memory tag) internal pure { for (uint256 i = 0; i < e.length; i++) { uint256 g; assembly { g := mload(add(m, shl(5, i))) } require(g == e[i], tag); } }
    function testPermVector0() public pure {
        uint256[] memory a; uint256[] memory e;
        a = new uint256[](16);
        a[0] = 0;
        a[1] = 0;
        a[2] = 0;
        a[3] = 0;
        a[4] = 0;
        a[5] = 0;
        a[6] = 0;
        a[7] = 0;
        a[8] = 0;
        a[9] = 0;
        a[10] = 0;
        a[11] = 0;
        a[12] = 0;
        a[13] = 0;
        a[14] = 0;
        a[15] = 0;
        e = new uint256[](16);
        e[0] = 10583491307417313222;
        e[1] = 8844572359363077260;
        e[2] = 11352777180032811984;
        e[3] = 9571995428655275277;
        e[4] = 12621271799844422439;
        e[5] = 4632067351883177911;
        e[6] = 14234244175178617089;
        e[7] = 17703052955947816234;
        e[8] = 1196022444482449693;
        e[9] = 3612770181656846067;
        e[10] = 15967954107062084062;
        e[11] = 3938936269738808304;
        e[12] = 15612650423412063454;
        e[13] = 117397693423305038;
        e[14] = 5832318384942062117;
        e[15] = 15941389909625905273;
        uint256 m = 0x4000; _load(a, m); P2G16.permute(m); _eq(m, e, "perm0");
    }
    function testPermVector1() public pure {
        uint256[] memory a; uint256[] memory e;
        a = new uint256[](16);
        a[0] = 0;
        a[1] = 1;
        a[2] = 2;
        a[3] = 3;
        a[4] = 4;
        a[5] = 5;
        a[6] = 6;
        a[7] = 7;
        a[8] = 8;
        a[9] = 9;
        a[10] = 10;
        a[11] = 11;
        a[12] = 12;
        a[13] = 13;
        a[14] = 14;
        a[15] = 15;
        e = new uint256[](16);
        e[0] = 6268302820292647768;
        e[1] = 10142015209694023484;
        e[2] = 1223357282450986885;
        e[3] = 5932746238325443059;
        e[4] = 5710675519399354050;
        e[5] = 103187318258722347;
        e[6] = 11189513079449365496;
        e[7] = 11012951990497953954;
        e[8] = 7587561495833552647;
        e[9] = 1455287115091150590;
        e[10] = 9817670256890116996;
        e[11] = 4862805749901149773;
        e[12] = 11330560706353363109;
        e[13] = 570257190817156331;
        e[14] = 4710494589994283300;
        e[15] = 3541695221596628273;
        uint256 m = 0x4000; _load(a, m); P2G16.permute(m); _eq(m, e, "perm1");
    }
    function testPermVector2() public pure {
        uint256[] memory a; uint256[] memory e;
        a = new uint256[](16);
        a[0] = 18446744069414584320;
        a[1] = 18446744069414584319;
        a[2] = 18446744069414584318;
        a[3] = 18446744069414584317;
        a[4] = 18446744069414584316;
        a[5] = 18446744069414584315;
        a[6] = 18446744069414584314;
        a[7] = 18446744069414584313;
        a[8] = 18446744069414584312;
        a[9] = 18446744069414584311;
        a[10] = 18446744069414584310;
        a[11] = 18446744069414584309;
        a[12] = 18446744069414584308;
        a[13] = 18446744069414584307;
        a[14] = 18446744069414584306;
        a[15] = 18446744069414584305;
        e = new uint256[](16);
        e[0] = 5227611305910290122;
        e[1] = 14025063362815849960;
        e[2] = 7069206701915326938;
        e[3] = 5656119407402070180;
        e[4] = 1172021160644352911;
        e[5] = 3514055033396736945;
        e[6] = 6350017899843054563;
        e[7] = 1095315807354332967;
        e[8] = 10362684257371971045;
        e[9] = 2381624794185871703;
        e[10] = 11011474584713512782;
        e[11] = 13587663318978077920;
        e[12] = 12961453863487850861;
        e[13] = 9966612811890175292;
        e[14] = 10081727427086544552;
        e[15] = 7929396504593997861;
        uint256 m = 0x4000; _load(a, m); P2G16.permute(m); _eq(m, e, "perm2");
    }
    function testHashSlice32() public pure {
        uint256[] memory a; uint256[] memory e;
        a = new uint256[](32);
        a[0] = 1000;
        a[1] = 1007;
        a[2] = 1014;
        a[3] = 1021;
        a[4] = 1028;
        a[5] = 1035;
        a[6] = 1042;
        a[7] = 1049;
        a[8] = 1056;
        a[9] = 1063;
        a[10] = 1070;
        a[11] = 1077;
        a[12] = 1084;
        a[13] = 1091;
        a[14] = 1098;
        a[15] = 1105;
        a[16] = 1112;
        a[17] = 1119;
        a[18] = 1126;
        a[19] = 1133;
        a[20] = 1140;
        a[21] = 1147;
        a[22] = 1154;
        a[23] = 1161;
        a[24] = 1168;
        a[25] = 1175;
        a[26] = 1182;
        a[27] = 1189;
        a[28] = 1196;
        a[29] = 1203;
        a[30] = 1210;
        a[31] = 1217;
        e = new uint256[](8);
        e[0] = 17245061850151333774;
        e[1] = 7809546851839537179;
        e[2] = 13423497604149535876;
        e[3] = 15433536249883890177;
        e[4] = 9850791784463953177;
        e[5] = 15368637227010744551;
        e[6] = 4219911282438087139;
        e[7] = 14193184448888533118;
        uint256 inp = 0x5000; _load(a, inp); uint256 st = 0x4000; uint256 perms = P2G16.hashSlice(st, inp, 32); require(perms == 4, "perms"); _eq(st, e, "hash32");
    }
    function testCompress2() public pure {
        uint256[] memory a; uint256[] memory b; uint256[] memory e;
        a = new uint256[](8);
        a[0] = 5;
        a[1] = 6;
        a[2] = 7;
        a[3] = 8;
        a[4] = 9;
        a[5] = 10;
        a[6] = 11;
        a[7] = 12;
        b = new uint256[](8);
        b[0] = 500;
        b[1] = 501;
        b[2] = 502;
        b[3] = 503;
        b[4] = 504;
        b[5] = 505;
        b[6] = 506;
        b[7] = 507;
        e = new uint256[](8);
        e[0] = 2803312217845805162;
        e[1] = 7176053453098906489;
        e[2] = 3498046892354008368;
        e[3] = 8221399756275268426;
        e[4] = 1355855345201892330;
        e[5] = 8836623947149141074;
        e[6] = 2720488493767385644;
        e[7] = 9548245496390081568;
        _load(a, 0x5000); _load(b, 0x5100); uint256 st = 0x4000; P2G16.compress2(st, 0x5000, 0x5100); _eq(st, e, "compress");
    }
    function testGas() public {
        uint256 m = 0x4000; for (uint256 i = 0; i < 16; i++) { assembly { mstore(add(m, shl(5, i)), add(i, 3)) } }
        uint256 g = gasleft(); P2G16.permute(m); uint256 gp = g - gasleft();
        emit log_named_uint("GAS one Poseidon2-Goldilocks-16 permutation", gp);
        uint256 inp = 0x5000; for (uint256 i = 0; i < 32; i++) { assembly { mstore(add(inp, shl(5, i)), add(i, 1000)) } }
        g = gasleft(); P2G16.hashSlice(m, inp, 32); uint256 gh = g - gasleft();
        emit log_named_uint("GAS leaf hash of 32 elements (4 perms)", gh);
        g = gasleft(); P2G16.compress2(m, 0x5000, 0x5100); uint256 gc = g - gasleft();
        emit log_named_uint("GAS 2-to-1 compress (1 perm)", gc);
    }
}
